import '@mantine/core/styles.layer.css';

import "~/shared/assets/styles/normalize.scss";
import "~/shared/assets/styles/fonts.scss";
import "~/shared/assets/styles/variables.scss";
import "~/shared/assets/styles/globals.scss";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps  } from "@mantine/core";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <TRPCReactProvider>
          <AuthKitProvider>
            <MantineProvider defaultColorScheme="dark">
              {children}
            </MantineProvider>
          </AuthKitProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
